export const speciesData = {
  Nekomimi: {
    ears: 'feline ears',
    features: ['whiskers', 'cat-like eyes'],
    personality: ['curious', 'playful', 'agile'],
    negative_prompt: 'extra limbs, extra heads, distorted anatomy, disjointed body parts, surreal shapes, blurry textures, missing features, duplicated elements, glitch effects, malformed faces',
    breed: 'cat',
  },
  Inumimi: {
    ears: 'floppy ears',
    features: ['loyal eyes', 'dog-like features'],
    personality: ['loyal', 'dependable', 'brave', 'confident'],
    negative_prompt: 'extra limbs, extra heads, distorted anatomy, disjointed body parts, surreal shapes, blurry textures, missing features, duplicated elements, glitch effects, malformed faces',
    breed: 'dog',
  },
  Kitsunemimi: {
    ears: 'fox ears',
    features: ['intelligent eyes', 'fox-like features'],
    personality: ['intelligent', 'cunning', 'scholarly', 'thoughtful'],
    negative_prompt: 'multiple tails, kimono, fantasy effects, ornate style, glitch effects, malformed anatomy',
    breed: 'fox',
  },
  Usagimimi: {
    ears: 'long rabbit ears',
    features: ['large eyes', 'rabbit-like features'],
    personality: ['shy', 'alert', 'cautious', 'timid', 'focused'],
    negative_prompt: 'extra limbs, extra heads, distorted anatomy, disjointed body parts, surreal shapes, blurry textures, missing features, duplicated elements, glitch effects, malformed faces',
    breed: 'rabbit',
  },
  Ookami: {
    ears: 'wolf ears',
    features: ['strong jawline', 'wolf-like features'],
    personality: ['strong', 'confident', 'assertive', 'bold', 'determined'],
    negative_prompt: 'extra limbs, extra heads, distorted anatomy, disjointed body parts, surreal shapes, blurry textures, missing features, duplicated elements, glitch effects, malformed faces',
    breed: 'wolf',
  },
  Nezumimi: {
    ears: 'round mouse ears',
    features: ['small frame', 'mouse-like features'],
    personality: ['resourceful', 'sly', 'serious', 'clever'],
    negative_prompt: 'extra limbs, extra heads, distorted anatomy, disjointed body parts, surreal shapes, blurry textures, missing features, duplicated elements, glitch effects, malformed faces',
    breed: 'mouse',
  },
  Ryūjin: {
    ears: 'small horns',
    features: ['scales on cheeks', 'dragon features', 'faint scales'],
    personality: ['calm', 'mysterious', 'powerful'],
    negative_prompt: 'extra limbs, wings, tails, surreal features, blurry textures, ornate armor, fantasy background, glitch effects, malformed faces',
    breed: 'dragon',
  },
  Tanukimimi: {
    ears: 'rounded tanuki ears',
    features: ['fluffy features', 'tanuki-like traits'],
    personality: ['playful', 'mischievous', 'cheerful'],
    negative_prompt: 'extra limbs, exaggerated tail, ornate clothing, fantasy elements, glitch effects, malformed faces',
    breed: 'tanuki',
  },
  Torimimi: {
    ears: 'feathered ear tufts',
    features: ['sharp eyes', 'feathery bangs', 'bird-like features'],
    personality: ['sharp', 'alert', 'focused'],
    negative_prompt: 'wings, flying pose, feathers on arms, fantasy background, glitch effects, malformed faces',
    breed: 'bird',
  },
  Kumamimi: {
    ears: 'round bear ears',
    features: ['strong build', 'bear-like features'],
    personality: ['reliable', 'calm', 'strong', 'steady'],
    negative_prompt: 'hulking build, bear paws, fur coat, fantasy setting, glitch effects, malformed faces',
    breed: 'bear',
  },
  Caprimimi: {
    ears: 'small curved horns',
    features: ['goat-like features', 'spiraling horns'],
    personality: ['calm', 'clever', 'thoughtful'],
    negative_prompt: 'extra limbs, ornate horn patterns, fantasy background, glitch effects, malformed faces',
    breed: 'goat',
  },
  Ushimimi: {
    ears: 'small cow horns',
    features: ['cow-like features', 'curved horns'],
    personality: ['calm', 'steady', 'reliable'],
    negative_prompt: 'udder, tail, cow spots on skin, fantasy setting, glitch effects, malformed faces',
    breed: 'cow',
  },
  Hebimimi: {
    ears: 'no visible ears',
    features: ['slitted eyes', 'snake scale patterns', 'serpentine features'],
    personality: ['mysterious', 'calm', 'elegant'],
    negative_prompt: 'snakes instead of hair, full body snake tail, fantasy background, ornate clothing, glitch effects, malformed anatomy',
    breed: 'snake',
  },
  Shikamimi: {
    ears: 'small antlers',
    features: ['deer-like features', 'gentle eyes'],
    personality: ['gentle', 'shy', 'graceful'],
    negative_prompt: 'deer legs, fantasy setting, elaborate clothing, glitch effects, malformed anatomy',
    breed: 'deer',
  },
  Koumori: {
    ears: 'pointed bat ears',
    features: ['wide eyes', 'bat-like features'],
    personality: ['mysterious', 'alert', 'nocturnal'],
    negative_prompt: 'bat wings, oversized ears, full fantasy costume, glitch effects, malformed anatomy',
    breed: 'bat',
  },
  Umamimi: {
    ears: 'upright horse ears',
    features: ['horse-like features', 'steady eyes'],
    personality: ['calm', 'steady', 'reliable'],
    negative_prompt: 'horse nose, tail in frame, racing outfit, glitch effects, malformed anatomy',
    breed: 'horse',
  },
};
